version: '2'
services:
  app:
    build: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - ./:/usr/src/app
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
      - "8080:8080"
    stdin_open: true
    tty: true
    env_file:
      - ./commons.env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: superacao_development
      POSTGRES_USER: superacao
      POSTGRES_PASSWORD: 123456
  redis:
    image: redis:3.0.7
    ports:
      - '6379:6379'
  sidekiq:
    build: ./
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./commons.env
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '4444:8080'
