# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bd27a1105b7dd09a102450fefa77ff9e4e19e4dd58dfe4e88b169c500b10ee1fcb120af5842b2b30938d41813ac78a3f455013ce49852f2563e7262d0f4ece6

test:
  secret_key_base: b79f2ffaeb208930056844087ed18076ed796d82706237534ea35ee3b4d67da8bb773d040d77516ee210c95dc3959ceadce34a8aa64e0c966bb71f9f4992d677

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
